/*
-- Query: SELECT * FROM Countries
-- Date: 2020-07-11 14:54
*/
USE country_db;

INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (1,'Afghanistan ',0,0,31056997,'ASIA (EX. NEAR EAST)');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (2,'Albania ',0,0,3581655,'EASTERN EUROPE');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (3,'Algeria ',0,0,32930091,'NORTHERN AFRICA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (4,'American Samoa ',0,0,57794,'OCEANIA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (5,'Andorra ',0,0,71201,'WESTERN EUROPE');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (6,'Angola ',0,0,12127071,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (7,'Anguilla ',0,0,13477,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (8,'Antigua & Barbuda ',0,0,69108,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (9,'Argentina ',0,0,39921833,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (10,'Armenia ',0,0,2976372,'C.W. OF IND. STATES');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (11,'Aruba ',0,0,71891,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (12,'Australia ',0,0,20264082,'OCEANIA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (13,'Austria ',0,0,8192880,'WESTERN EUROPE');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (14,'Azerbaijan ',0,0,7961619,'C.W. OF IND. STATES');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (15,'Bahamas, The ',0,0,303770,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (16,'Bahrain ',0,0,698585,'NEAR EAST');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (17,'Bangladesh ',0,0,147365352,'ASIA (EX. NEAR EAST)');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (18,'Barbados ',0,0,279912,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (19,'Belarus ',0,0,10293011,'C.W. OF IND. STATES');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (20,'Belgium ',0,0,10379067,'WESTERN EUROPE');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (21,'Belize ',0,0,287730,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (22,'Benin ',0,0,7862944,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (23,'Bermuda ',0,0,65773,'NORTHERN AMERICA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (24,'Bhutan ',0,0,2279723,'ASIA (EX. NEAR EAST)');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (25,'Bolivia ',0,0,8989046,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (26,'Bosnia & Herzegovina ',0,0,4498976,'EASTERN EUROPE');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (27,'Botswana ',0,0,1639833,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (28,'Brazil ',0,0,188078227,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (29,'British Virgin Is. ',0,0,23098,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (30,'Brunei ',0,0,379444,'ASIA (EX. NEAR EAST)');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (31,'Bulgaria ',0,0,7385367,'EASTERN EUROPE');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (32,'Burkina Faso ',0,0,13902972,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (33,'Burma ',0,0,47382633,'ASIA (EX. NEAR EAST)');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (34,'Burundi ',0,0,8090068,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (35,'Cambodia ',0,0,13881427,'ASIA (EX. NEAR EAST)');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (36,'Cameroon ',0,0,17340702,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (37,'Canada ',0,0,33098932,'NORTHERN AMERICA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (38,'Cape Verde ',0,0,420979,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (39,'Cayman Islands ',0,0,45436,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (40,'Central African Rep. ',0,0,4303356,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (41,'Chad ',0,0,9944201,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (42,'Chile ',0,0,16134219,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (43,'China ',0,0,1313973713,'ASIA (EX. NEAR EAST)');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (44,'Colombia ',0,0,43593035,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (45,'Comoros ',0,0,690948,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (46,'Congo, Dem. Rep. ',0,0,62660551,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (47,'Congo, Repub. of the ',0,0,3702314,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (48,'Cook Islands ',0,0,21388,'OCEANIA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (49,'Costa Rica ',0,0,4075261,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (50,'Cote d\'Ivoire ',0,0,17654843,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (51,'Croatia ',0,0,4494749,'EASTERN EUROPE');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (52,'Cuba ',0,0,11382820,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (53,'Cyprus ',0,0,784301,'NEAR EAST');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (54,'Czech Republic ',0,0,10235455,'EASTERN EUROPE');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (55,'Denmark ',0,0,5450661,'WESTERN EUROPE');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (56,'Djibouti ',0,0,486530,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (57,'Dominica ',0,0,68910,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (58,'Dominican Republic ',0,0,9183984,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (59,'East Timor ',0,0,1062777,'ASIA (EX. NEAR EAST)');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (60,'Ecuador ',0,0,13547510,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (61,'Egypt ',0,0,78887007,'NORTHERN AFRICA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (62,'El Salvador ',0,0,6822378,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (63,'Equatorial Guinea ',0,0,540109,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (64,'Eritrea ',0,0,4786994,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (65,'Estonia ',0,0,1324333,'BALTICS');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (66,'Ethiopia ',0,0,74777981,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (67,'Faroe Islands ',0,0,47246,'WESTERN EUROPE');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (68,'Fiji ',0,0,905949,'OCEANIA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (69,'Finland ',0,0,5231372,'WESTERN EUROPE');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (70,'France ',0,0,60876136,'WESTERN EUROPE');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (71,'French Guiana ',0,0,199509,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (72,'French Polynesia ',0,0,274578,'OCEANIA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (73,'Gabon ',0,0,1424906,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (74,'Gambia, The ',0,0,1641564,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (75,'Gaza Strip ',0,0,1428757,'NEAR EAST');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (76,'Georgia ',0,0,4661473,'C.W. OF IND. STATES');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (77,'Germany ',0,0,82422299,'WESTERN EUROPE');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (78,'Ghana ',0,0,22409572,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (79,'Gibraltar ',0,0,27928,'WESTERN EUROPE');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (80,'Greece ',0,0,10688058,'WESTERN EUROPE');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (81,'Greenland ',0,0,56361,'NORTHERN AMERICA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (82,'Grenada ',0,0,89703,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (83,'Guadeloupe ',0,0,452776,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (84,'Guam ',0,0,171019,'OCEANIA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (85,'Guatemala ',0,0,12293545,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (86,'Guernsey ',0,0,65409,'WESTERN EUROPE');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (87,'Guinea ',0,0,9690222,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (88,'Guinea-Bissau ',0,0,1442029,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (89,'Guyana ',0,0,767245,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (90,'Haiti ',0,0,8308504,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (91,'Honduras ',0,0,7326496,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (92,'Hong Kong ',0,0,6940432,'ASIA (EX. NEAR EAST)');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (93,'Hungary ',0,0,9981334,'EASTERN EUROPE');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (94,'Iceland ',0,0,299388,'WESTERN EUROPE');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (95,'India ',0,0,1095351995,'ASIA (EX. NEAR EAST)');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (96,'Indonesia ',0,0,245452739,'ASIA (EX. NEAR EAST)');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (97,'Iran ',0,0,68688433,'ASIA (EX. NEAR EAST)');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (98,'Iraq ',0,0,26783383,'NEAR EAST');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (99,'Ireland ',0,0,4062235,'WESTERN EUROPE');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (100,'Isle of Man ',0,0,75441,'WESTERN EUROPE');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (101,'Israel ',0,0,6352117,'NEAR EAST');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (102,'Italy ',0,0,58133509,'WESTERN EUROPE');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (103,'Jamaica ',0,0,2758124,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (104,'Japan ',0,0,127463611,'ASIA (EX. NEAR EAST)');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (105,'Jersey ',0,0,91084,'WESTERN EUROPE');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (106,'Jordan ',0,0,5906760,'NEAR EAST');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (107,'Kazakhstan ',0,0,15233244,'C.W. OF IND. STATES');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (108,'Kenya ',0,0,34707817,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (109,'Kiribati ',0,0,105432,'OCEANIA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (110,'Korea, North ',0,0,23113019,'ASIA (EX. NEAR EAST)');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (111,'Korea, South ',0,0,48846823,'ASIA (EX. NEAR EAST)');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (112,'Kuwait ',0,0,2418393,'NEAR EAST');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (113,'Kyrgyzstan ',0,0,5213898,'C.W. OF IND. STATES');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (114,'Laos ',0,0,6368481,'ASIA (EX. NEAR EAST)');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (115,'Latvia ',0,0,2274735,'BALTICS');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (116,'Lebanon ',0,0,3874050,'NEAR EAST');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (117,'Lesotho ',0,0,2022331,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (118,'Liberia ',0,0,3042004,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (119,'Libya ',0,0,5900754,'NORTHERN AFRICA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (120,'Liechtenstein ',0,0,33987,'WESTERN EUROPE');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (121,'Lithuania ',0,0,3585906,'BALTICS');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (122,'Luxembourg ',0,0,474413,'WESTERN EUROPE');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (123,'Macau ',0,0,453125,'ASIA (EX. NEAR EAST)');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (124,'Macedonia ',0,0,2050554,'EASTERN EUROPE');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (125,'Madagascar ',0,0,18595469,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (126,'Malawi ',0,0,13013926,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (127,'Malaysia ',0,0,24385858,'ASIA (EX. NEAR EAST)');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (128,'Maldives ',0,0,359008,'ASIA (EX. NEAR EAST)');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (129,'Mali ',0,0,11716829,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (130,'Malta ',0,0,400214,'WESTERN EUROPE');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (131,'Marshall Islands ',0,0,60422,'OCEANIA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (132,'Martinique ',0,0,436131,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (133,'Mauritania ',0,0,3177388,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (134,'Mauritius ',0,0,1240827,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (135,'Mayotte ',0,0,201234,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (136,'Mexico ',0,0,107449525,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (137,'Micronesia, Fed. St. ',0,0,108004,'OCEANIA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (138,'Moldova ',0,0,4466706,'C.W. OF IND. STATES');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (139,'Monaco ',0,0,32543,'WESTERN EUROPE');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (140,'Mongolia ',0,0,2832224,'ASIA (EX. NEAR EAST)');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (141,'Montserrat ',0,0,9439,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (142,'Morocco ',0,0,33241259,'NORTHERN AFRICA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (143,'Mozambique ',0,0,19686505,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (144,'Namibia ',0,0,2044147,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (145,'Nauru ',0,0,13287,'OCEANIA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (146,'Nepal ',0,0,28287147,'ASIA (EX. NEAR EAST)');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (147,'Netherlands ',0,0,16491461,'WESTERN EUROPE');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (148,'Netherlands Antilles ',0,0,221736,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (149,'New Caledonia ',0,0,219246,'OCEANIA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (150,'New Zealand ',0,0,4076140,'OCEANIA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (151,'Nicaragua ',0,0,5570129,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (152,'Niger ',0,0,12525094,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (153,'Nigeria ',0,0,131859731,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (154,'N. Mariana Islands ',0,0,82459,'OCEANIA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (155,'Norway ',0,0,4610820,'WESTERN EUROPE');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (156,'Oman ',0,0,3102229,'NEAR EAST');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (157,'Pakistan ',0,0,165803560,'ASIA (EX. NEAR EAST)');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (158,'Palau ',0,0,20579,'OCEANIA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (159,'Panama ',0,0,3191319,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (160,'Papua New Guinea ',0,0,5670544,'OCEANIA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (161,'Paraguay ',0,0,6506464,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (162,'Peru ',0,0,28302603,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (163,'Philippines ',0,0,89468677,'ASIA (EX. NEAR EAST)');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (164,'Poland ',0,0,38536869,'EASTERN EUROPE');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (165,'Portugal ',0,0,10605870,'WESTERN EUROPE');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (166,'Puerto Rico ',0,0,3927188,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (167,'Qatar ',0,0,885359,'NEAR EAST');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (168,'Reunion ',0,0,787584,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (169,'Romania ',0,0,22303552,'EASTERN EUROPE');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (170,'Russia ',0,0,142893540,'C.W. OF IND. STATES');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (171,'Rwanda ',0,0,8648248,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (172,'Saint Helena ',0,0,7502,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (173,'Saint Kitts & Nevis ',0,0,39129,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (174,'Saint Lucia ',0,0,168458,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (175,'St Pierre & Miquelon ',0,0,7026,'NORTHERN AMERICA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (176,'Saint Vincent and the Grenadines ',0,0,117848,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (177,'Samoa ',0,0,176908,'OCEANIA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (178,'San Marino ',0,0,29251,'WESTERN EUROPE');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (179,'Sao Tome & Principe ',0,0,193413,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (180,'Saudi Arabia ',0,0,27019731,'NEAR EAST');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (181,'Senegal ',0,0,11987121,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (182,'Serbia ',0,0,9396411,'EASTERN EUROPE');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (183,'Seychelles ',0,0,81541,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (184,'Sierra Leone ',0,0,6005250,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (185,'Singapore ',0,0,4492150,'ASIA (EX. NEAR EAST)');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (186,'Slovakia ',0,0,5439448,'EASTERN EUROPE');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (187,'Slovenia ',0,0,2010347,'EASTERN EUROPE');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (188,'Solomon Islands ',0,0,552438,'OCEANIA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (189,'Somalia ',0,0,8863338,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (190,'South Africa ',0,0,44187637,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (191,'Spain ',0,0,40397842,'WESTERN EUROPE');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (192,'Sri Lanka ',0,0,20222240,'ASIA (EX. NEAR EAST)');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (193,'Sudan ',0,0,41236378,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (194,'Suriname ',0,0,439117,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (195,'Swaziland ',0,0,1136334,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (196,'Sweden ',0,0,9016596,'WESTERN EUROPE');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (197,'Switzerland ',0,0,7523934,'WESTERN EUROPE');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (198,'Syria ',0,0,18881361,'NEAR EAST');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (199,'Taiwan ',0,0,23036087,'ASIA (EX. NEAR EAST)');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (200,'Tajikistan ',0,0,7320815,'C.W. OF IND. STATES');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (201,'Tanzania ',0,0,37445392,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (202,'Thailand ',0,0,64631595,'ASIA (EX. NEAR EAST)');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (203,'Togo ',0,0,5548702,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (204,'Tonga ',0,0,114689,'OCEANIA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (205,'Trinidad & Tobago ',0,0,1065842,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (206,'Tunisia ',0,0,10175014,'NORTHERN AFRICA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (207,'Turkey ',0,0,70413958,'NEAR EAST');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (208,'Turkmenistan ',0,0,5042920,'C.W. OF IND. STATES');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (209,'Turks & Caicos Is ',0,0,21152,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (210,'Tuvalu ',0,0,11810,'OCEANIA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (211,'Uganda ',0,0,28195754,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (212,'Ukraine ',0,0,46710816,'C.W. OF IND. STATES');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (213,'United Arab Emirates ',0,0,2602713,'NEAR EAST');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (214,'United Kingdom ',0,0,60609153,'WESTERN EUROPE');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (215,'United States ',0,0,298444215,'NORTHERN AMERICA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (216,'Uruguay ',0,0,3431932,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (217,'Uzbekistan ',0,0,27307134,'C.W. OF IND. STATES');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (218,'Vanuatu ',0,0,208869,'OCEANIA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (219,'Venezuela ',0,0,25730435,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (220,'Vietnam ',0,0,84402966,'ASIA (EX. NEAR EAST)');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (221,'Virgin Islands ',0,0,108605,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (222,'Wallis and Futuna ',0,0,16025,'OCEANIA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (223,'West Bank ',0,0,2460492,'NEAR EAST');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (224,'Western Sahara ',0,0,273008,'NORTHERN AFRICA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (225,'Yemen ',0,0,21456188,'NEAR EAST');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (226,'Zambia ',0,0,11502010,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`id`,`country_name`,`desired`,`visited`,`population`,`region`) VALUES (227,'Zimbabwe ',0,0,12236805,'SUB-SAHARAN AFRICA');
