/*
-- Query: SELECT * FROM Countries
-- Date: 2020-07-11 14:54
*/
USE country_db;

INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Afghanistan ',0,0,31056997,'ASIA (EX. NEAR EAST)');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Albania ',0,0,3581655,'EASTERN EUROPE');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Algeria ',0,0,32930091,'NORTHERN AFRICA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('American Samoa ',0,0,57794,'OCEANIA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Andorra ',0,0,71201,'WESTERN EUROPE');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Angola ',0,0,12127071,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Anguilla ',0,0,13477,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Antigua & Barbuda ',0,0,69108,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Argentina ',0,0,39921833,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Armenia ',0,0,2976372,'C.W. OF IND. STATES');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Aruba ',0,0,71891,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Australia ',0,0,20264082,'OCEANIA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Austria ',0,0,8192880,'WESTERN EUROPE');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Azerbaijan ',0,0,7961619,'C.W. OF IND. STATES');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Bahamas, The ',0,0,303770,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Bahrain ',0,0,698585,'NEAR EAST');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Bangladesh ',0,0,147365352,'ASIA (EX. NEAR EAST)');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Barbados ',0,0,279912,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Belarus ',0,0,10293011,'C.W. OF IND. STATES');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Belgium ',0,0,10379067,'WESTERN EUROPE');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Belize ',0,0,287730,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Benin ',0,0,7862944,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Bermuda ',0,0,65773,'NORTHERN AMERICA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Bhutan ',0,0,2279723,'ASIA (EX. NEAR EAST)');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Bolivia ',0,0,8989046,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Bosnia & Herzegovina ',0,0,4498976,'EASTERN EUROPE');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Botswana ',0,0,1639833,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Brazil ',0,0,188078227,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('British Virgin Is. ',0,0,23098,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Brunei ',0,0,379444,'ASIA (EX. NEAR EAST)');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Bulgaria ',0,0,7385367,'EASTERN EUROPE');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Burkina Faso ',0,0,13902972,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Burma ',0,0,47382633,'ASIA (EX. NEAR EAST)');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Burundi ',0,0,8090068,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Cambodia ',0,0,13881427,'ASIA (EX. NEAR EAST)');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Cameroon ',0,0,17340702,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Canada ',0,0,33098932,'NORTHERN AMERICA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Cape Verde ',0,0,420979,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Cayman Islands ',0,0,45436,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Central African Rep. ',0,0,4303356,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Chad ',0,0,9944201,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Chile ',0,0,16134219,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('China ',0,0,1313973713,'ASIA (EX. NEAR EAST)');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Colombia ',0,0,43593035,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Comoros ',0,0,690948,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Congo, Dem. Rep. ',0,0,62660551,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Congo, Repub. of the ',0,0,3702314,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Cook Islands ',0,0,21388,'OCEANIA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Costa Rica ',0,0,4075261,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Cote d\'Ivoire ',0,0,17654843,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Croatia ',0,0,4494749,'EASTERN EUROPE');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Cuba ',0,0,11382820,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Cyprus ',0,0,784301,'NEAR EAST');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Czech Republic ',0,0,10235455,'EASTERN EUROPE');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Denmark ',0,0,5450661,'WESTERN EUROPE');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Djibouti ',0,0,486530,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Dominica ',0,0,68910,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Dominican Republic ',0,0,9183984,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('East Timor ',0,0,1062777,'ASIA (EX. NEAR EAST)');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Ecuador ',0,0,13547510,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Egypt ',0,0,78887007,'NORTHERN AFRICA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('El Salvador ',0,0,6822378,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Equatorial Guinea ',0,0,540109,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Eritrea ',0,0,4786994,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Estonia ',0,0,1324333,'BALTICS');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Ethiopia ',0,0,74777981,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Faroe Islands ',0,0,47246,'WESTERN EUROPE');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Fiji ',0,0,905949,'OCEANIA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Finland ',0,0,5231372,'WESTERN EUROPE');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('France ',0,0,60876136,'WESTERN EUROPE');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('French Guiana ',0,0,199509,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('French Polynesia ',0,0,274578,'OCEANIA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Gabon ',0,0,1424906,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Gambia, The ',0,0,1641564,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Gaza Strip ',0,0,1428757,'NEAR EAST');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Georgia ',0,0,4661473,'C.W. OF IND. STATES');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Germany ',0,0,82422299,'WESTERN EUROPE');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Ghana ',0,0,22409572,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Gibraltar ',0,0,27928,'WESTERN EUROPE');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Greece ',0,0,10688058,'WESTERN EUROPE');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Greenland ',0,0,56361,'NORTHERN AMERICA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Grenada ',0,0,89703,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Guadeloupe ',0,0,452776,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Guam ',0,0,171019,'OCEANIA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Guatemala ',0,0,12293545,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Guernsey ',0,0,65409,'WESTERN EUROPE');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Guinea ',0,0,9690222,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Guinea-Bissau ',0,0,1442029,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Guyana ',0,0,767245,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Haiti ',0,0,8308504,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Honduras ',0,0,7326496,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Hong Kong ',0,0,6940432,'ASIA (EX. NEAR EAST)');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Hungary ',0,0,9981334,'EASTERN EUROPE');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Iceland ',0,0,299388,'WESTERN EUROPE');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('India ',0,0,1095351995,'ASIA (EX. NEAR EAST)');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Indonesia ',0,0,245452739,'ASIA (EX. NEAR EAST)');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Iran ',0,0,68688433,'ASIA (EX. NEAR EAST)');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Iraq ',0,0,26783383,'NEAR EAST');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Ireland ',0,0,4062235,'WESTERN EUROPE');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Isle of Man ',0,0,75441,'WESTERN EUROPE');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Israel ',0,0,6352117,'NEAR EAST');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Italy ',0,0,58133509,'WESTERN EUROPE');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Jamaica ',0,0,2758124,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Japan ',0,0,127463611,'ASIA (EX. NEAR EAST)');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Jersey ',0,0,91084,'WESTERN EUROPE');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Jordan ',0,0,5906760,'NEAR EAST');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Kazakhstan ',0,0,15233244,'C.W. OF IND. STATES');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Kenya ',0,0,34707817,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Kiribati ',0,0,105432,'OCEANIA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Korea, North ',0,0,23113019,'ASIA (EX. NEAR EAST)');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Korea, South ',0,0,48846823,'ASIA (EX. NEAR EAST)');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Kuwait ',0,0,2418393,'NEAR EAST');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Kyrgyzstan ',0,0,5213898,'C.W. OF IND. STATES');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Laos ',0,0,6368481,'ASIA (EX. NEAR EAST)');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Latvia ',0,0,2274735,'BALTICS');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Lebanon ',0,0,3874050,'NEAR EAST');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Lesotho ',0,0,2022331,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Liberia ',0,0,3042004,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Libya ',0,0,5900754,'NORTHERN AFRICA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Liechtenstein ',0,0,33987,'WESTERN EUROPE');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Lithuania ',0,0,3585906,'BALTICS');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Luxembourg ',0,0,474413,'WESTERN EUROPE');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Macau ',0,0,453125,'ASIA (EX. NEAR EAST)');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Macedonia ',0,0,2050554,'EASTERN EUROPE');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Madagascar ',0,0,18595469,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Malawi ',0,0,13013926,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Malaysia ',0,0,24385858,'ASIA (EX. NEAR EAST)');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Maldives ',0,0,359008,'ASIA (EX. NEAR EAST)');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Mali ',0,0,11716829,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Malta ',0,0,400214,'WESTERN EUROPE');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Marshall Islands ',0,0,60422,'OCEANIA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Martinique ',0,0,436131,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Mauritania ',0,0,3177388,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Mauritius ',0,0,1240827,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Mayotte ',0,0,201234,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Mexico ',0,0,107449525,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Micronesia, Fed. St. ',0,0,108004,'OCEANIA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Moldova ',0,0,4466706,'C.W. OF IND. STATES');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Monaco ',0,0,32543,'WESTERN EUROPE');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Mongolia ',0,0,2832224,'ASIA (EX. NEAR EAST)');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Montserrat ',0,0,9439,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Morocco ',0,0,33241259,'NORTHERN AFRICA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Mozambique ',0,0,19686505,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Namibia ',0,0,2044147,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Nauru ',0,0,13287,'OCEANIA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Nepal ',0,0,28287147,'ASIA (EX. NEAR EAST)');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Netherlands ',0,0,16491461,'WESTERN EUROPE');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Netherlands Antilles ',0,0,221736,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('New Caledonia ',0,0,219246,'OCEANIA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('New Zealand ',0,0,4076140,'OCEANIA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Nicaragua ',0,0,5570129,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Niger ',0,0,12525094,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Nigeria ',0,0,131859731,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('N. Mariana Islands ',0,0,82459,'OCEANIA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Norway ',0,0,4610820,'WESTERN EUROPE');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Oman ',0,0,3102229,'NEAR EAST');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Pakistan ',0,0,165803560,'ASIA (EX. NEAR EAST)');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Palau ',0,0,20579,'OCEANIA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Panama ',0,0,3191319,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Papua New Guinea ',0,0,5670544,'OCEANIA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Paraguay ',0,0,6506464,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Peru ',0,0,28302603,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Philippines ',0,0,89468677,'ASIA (EX. NEAR EAST)');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Poland ',0,0,38536869,'EASTERN EUROPE');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Portugal ',0,0,10605870,'WESTERN EUROPE');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Puerto Rico ',0,0,3927188,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Qatar ',0,0,885359,'NEAR EAST');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Reunion ',0,0,787584,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Romania ',0,0,22303552,'EASTERN EUROPE');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Russia ',0,0,142893540,'C.W. OF IND. STATES');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Rwanda ',0,0,8648248,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Saint Helena ',0,0,7502,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Saint Kitts & Nevis ',0,0,39129,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Saint Lucia ',0,0,168458,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('St Pierre & Miquelon ',0,0,7026,'NORTHERN AMERICA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Saint Vincent and the Grenadines ',0,0,117848,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Samoa ',0,0,176908,'OCEANIA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('San Marino ',0,0,29251,'WESTERN EUROPE');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Sao Tome & Principe ',0,0,193413,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Saudi Arabia ',0,0,27019731,'NEAR EAST');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Senegal ',0,0,11987121,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Serbia ',0,0,9396411,'EASTERN EUROPE');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Seychelles ',0,0,81541,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Sierra Leone ',0,0,6005250,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Singapore ',0,0,4492150,'ASIA (EX. NEAR EAST)');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Slovakia ',0,0,5439448,'EASTERN EUROPE');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Slovenia ',0,0,2010347,'EASTERN EUROPE');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Solomon Islands ',0,0,552438,'OCEANIA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Somalia ',0,0,8863338,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('South Africa ',0,0,44187637,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Spain ',0,0,40397842,'WESTERN EUROPE');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Sri Lanka ',0,0,20222240,'ASIA (EX. NEAR EAST)');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Sudan ',0,0,41236378,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Suriname ',0,0,439117,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Swaziland ',0,0,1136334,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Sweden ',0,0,9016596,'WESTERN EUROPE');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Switzerland ',0,0,7523934,'WESTERN EUROPE');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Syria ',0,0,18881361,'NEAR EAST');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Taiwan ',0,0,23036087,'ASIA (EX. NEAR EAST)');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Tajikistan ',0,0,7320815,'C.W. OF IND. STATES');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Tanzania ',0,0,37445392,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Thailand ',0,0,64631595,'ASIA (EX. NEAR EAST)');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Togo ',0,0,5548702,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Tonga ',0,0,114689,'OCEANIA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Trinidad & Tobago ',0,0,1065842,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Tunisia ',0,0,10175014,'NORTHERN AFRICA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Turkey ',0,0,70413958,'NEAR EAST');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Turkmenistan ',0,0,5042920,'C.W. OF IND. STATES');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Turks & Caicos Is ',0,0,21152,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Tuvalu ',0,0,11810,'OCEANIA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Uganda ',0,0,28195754,'SUB-SAHARAN AFRICA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Ukraine ',0,0,46710816,'C.W. OF IND. STATES');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('United Arab Emirates ',0,0,2602713,'NEAR EAST');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('United Kingdom ',0,0,60609153,'WESTERN EUROPE');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('United States ',0,0,298444215,'NORTHERN AMERICA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Uruguay ',0,0,3431932,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Uzbekistan ',0,0,27307134,'C.W. OF IND. STATES');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Vanuatu ',0,0,208869,'OCEANIA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Venezuela ',0,0,25730435,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Vietnam ',0,0,84402966,'ASIA (EX. NEAR EAST)');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Virgin Islands ',0,0,108605,'LATIN AMER. & CARIB');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Wallis and Futuna ',0,0,16025,'OCEANIA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('West Bank ',0,0,2460492,'NEAR EAST');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Western Sahara ',0,0,273008,'NORTHERN AFRICA');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Yemen ',0,0,21456188,'NEAR EAST');
INSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES ('Zambia ',0,0,11502010,'SUB-SAHARAN AFRICAINSERT INTO `Countries` (`country_name`,`desired`,`visited`,`population`,`region`) VALUES (227,'Zimbabwe ',0,0,12236805,'SUB-SAHARAN AFRICA');
 